[connections.snowflake]
account=TOGEXEZ_MX28295
user="RAYALAVENKAT4247"
password="TrainSelf@8998"
role="SYSADMIN"
warehouse="COMPUTE_WH"
database="SMOOTHIES"
schema="PUBLIC"
client_session_keep_alive=true
